language: php

php:
  - 7.1.11
  - 7.1.0
  - 7.1
  - 7.0.25
  - 7.0.0
  - 7.0
  - 5.6.31
  - 5.6.0
  - 5.6
  - 5.5.38
  - 5.5
  - 5.4.45
  - 5.4

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

matrix:
  allow_failures:
    - php: 7.2

script:
  - find . \( -name '*.php' \) -exec php -lf {} \;

notifications:
  email: false


